DistanceEd/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myappF23/', include('myappF23.urls')),
]

myappF23/urls.py
from django.urls import path
from myappF23 import views

app_name = 'myappF23'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'courses/', views.courses, name='courses'),
    path(r'test/<int:pk>', views.TestView.as_view(), name='test-detail'),
    path(r'<int:category_no>/', views.detail, name='detail'),
    path(r'instructor/<int:instructor_id>/', views.instructor_detail, name='instructor_detail'),
    path(r'place-order', views.place_order, name='place_order'),
    path(r'courses/<course_id>',views.coursedetail,name="courses_detail"),
    path(r'login/',views.user_login,name='login'),
    path(r'logout/',views.user_logout,name='logout'),
    path(r'myaccount/',views.myaccount,name='myaccount'),
    path(r'set_cookie/', views.set_test_cookie, name='set_test_cookie'),
    path(r'check_cookie/', views.check_test_cookie, name='check_test_cookie'),
    path(r'delete_cookie/', views.delete_test_cookie, name='delete_test_cookie'),
]

myappF23/models.py
from django.db import models
from decimal import Decimal
from django.contrib.auth.models import User

class Student(User):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    STUDENT_STATUS_CHOICES = [
        ('ER', 'Enrolled'),
        ('SP', 'Suspended'),
        ('GD', 'Graduated'), ]
    # first_name = models.CharField(max_length=100)
    # last_name = models.CharField(max_length=100)
    # email = models.EmailField(max_length=100,unique=True)
    date_of_birth = models.DateField()
    status = models.CharField(max_length=10, choices=STUDENT_STATUS_CHOICES, default='ER')
    # courses_interested = models.ManyToManyField('Course', related_name='interested_students', blank=True)

    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Students'
    def __str__(self):
        return self.first_name + " "+self.last_name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



class Instructor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField()
    students= models.ManyToManyField(Student)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Course(models.Model):
    COURSE_LEVEL_CHOICES = [
        (1, 'Beginner'),
        (2, 'Intermediate'),
        (3, 'Advanced'), ]
    title = models.CharField(max_length=200)
    description = models.TextField()
    instructor = models.ForeignKey(Instructor,on_delete=models.CASCADE)
    categories = models.ForeignKey(Category,on_delete=models.CASCADE)
    students = models.ManyToManyField(Student, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    levels = models.PositiveIntegerField(choices=COURSE_LEVEL_CHOICES,default=1)
    interested= models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        (0, 'Order Confirmed'),
        (1, 'Order Cancelled'),
        ]
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    student=models.ForeignKey(Student,on_delete=models.CASCADE)
    order_date=models.DateField()
    order_status = models.IntegerField( choices=ORDER_STATUS_CHOICES, default=1)
    order_price = models.DecimalField(max_digits=10, decimal_places=2,default=0.0)
    levels=models.PositiveIntegerField(default=1)

    def clean(self):
        if self.levels > self.course.levels:
            raise ValidationError(_('Invalid number of levels for this course.'))
    def discount(self):
        self.order_price= self.course.price-(self.course.price*Decimal(0.1))
        self.save()

    def __str__(self):
        return f"{self.course} - {self.student} ${self.order_price}"

myappF23/forms.py
from django import forms
from myappF23.models import Order


class InterestForm(forms.Form):
    CHOICES = [(1, 'Yes'), (0, 'No')]
    interested = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'radio-input'}),choices=CHOICES, required=True)
    level=forms.IntegerField(min_value=1,max_value=5,initial=1)
    additional_comments=forms.CharField(label='Additional Comments',widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}),required=False)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["student", "course", "levels", "order_date"]

        widget={
            'student': forms.RadioSelect(),
            'order_date': forms.SelectDateWidget(),
        }

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

myappF23/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from .models import Category, Course, Student, Instructor,Order
from .forms import InterestForm,OrderForm,LoginForm
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.urls import reverse
from datetime import datetime, timedelta
from django.contrib.sessions.models import Session
from django.utils import timezone

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.get(username=username)
            user = authenticate(request,username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    utc_now = datetime.now(timezone.utc)
                    eastern = timezone.get_fixed_timezone(timedelta(hours=-5))
                    eastern_time = utc_now.astimezone(eastern)
                    request.session['last_login_info'] = eastern_time.strftime('%Y-%m-%d %H:%M:%S')
                    request.session.set_expiry(300)
                    return HttpResponseRedirect(reverse('myappF23:index'))
                else:
                    return HttpResponse('Your account is disabled.')
            else:
                return HttpResponse('Invalid login details.')
    else:
        form = LoginForm()

    return render(request, 'myappF23/login.html', {'form': form})

@login_required
def user_logout(request):
    request.session.flush()
    # logout(request)
    return HttpResponseRedirect(reverse(('myappF23:login')))


def index(request):
    cookie=0
    if 'user_visits' in request.COOKIES:
        cookie = request.COOKIES.get('user_visits', 0)
        cookie = int(cookie) + 1
    last_login_info = request.session.get('last_login_info')
    if last_login_info:
        message = f'Your last login was at: {last_login_info}'
    else:
        message = 'Your last login was more than 5 minutes ago'
    category_list = Category.objects.all().order_by('id')[:10]
    instructor_list = Instructor.objects.all().order_by('id')[:10]
    response = render(request, 'myappF23/index.html', {'category_list': category_list,'instructor_list':instructor_list,'cookie_count':cookie,'message':message})
    response.set_cookie('user_visits', cookie, max_age=10)
    return response


def about(request):
    response = HttpResponse("hello")
    response.set_cookie('user_visits', 0)
    return render(request,'myappF23/about.html')


class TestView(DetailView):
    model=Category
    template_name="myappF23/test.html"
    context_object_name = 'category'

def detail(request,category_no):
    category = get_object_or_404(Category,pk=category_no)

    courses=category.course_set.all()
    return render(request,'myappF23/detail.html',{"category":str(category),"courses":courses})

def instructor_detail(request,instructor_id):
    instructor = get_object_or_404(Instructor,pk=instructor_id)

    courses=instructor.course_set.all()

    students=instructor.students.all()

    return render(request,'myappF23/instructor_detail.html', {
        "instructor":instructor,
        "courses":courses,
        "students":students
    })

def courses(request):
    courses=Course.objects.all().order_by('id')
    return render(request,'myappF23/courses.html', {
    "courses":courses, })

def place_order(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)

        if form.is_valid():
            order = form.save(commit=False)
            if order.levels > order.course.levels:
                msg = 'You exceeded the number of levels for this course.'
                return render(request, 'myappF23/order_response.html', {'msg': msg})
            order.order_price = order.course.price
            if order.course.price > 150.00:
                order.discount()
            order.order_status = 0
            order.save()
            msg = 'Your course has been ordered successfully.'
        else:
            msg = 'You exceeded the number of levels for this course.'
        return render(request, 'myappF23/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myappF23/placeorder.html', {'form': form, 'msg': msg, 'courlist': courlist})

def coursedetail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    form = InterestForm()
    if request.method=='POST':
        form=InterestForm(request.POST)
        if form.is_valid():
            interested = form.cleaned_data['interested']
            level = form.cleaned_data['level']
            additional_comments = form.cleaned_data['additional_comments']
            if interested == '1':
                course.interested += 1
                course.save()
            return redirect('myappF23:courses')
    return render(request,'myappF23/coursedetail.html',{'course':course,'form':form})

@login_required
def myaccount(request):
    user = request.user
    if hasattr(user, 'student'):
        student = user
        courses_ordered = Order.objects.filter(student=student)
        courses_interested = Course.objects.filter(students=student)
        context = {
            'full_name': f"{student.first_name} {student.last_name}",
            'courses_ordered': courses_ordered,
            'courses_interested': courses_interested,
            'is_student': True,
        }

        return render(request, 'myappF23/myaccount.html', context)
    else:
        return HttpResponse('You are not a registered student!')

def set_test_cookie(request):
    response = HttpResponse("Setting a test cookie")
    response.set_cookie('test_cookie', 'test_value')
    return response

def check_test_cookie(request):
    if 'test_cookie' in request.COOKIES:
        return HttpResponse("Test cookie is set! <a href='/myappF23/delete_cookie/'>Delete Cookie</a>")
    else:
        return HttpResponse("Test cookie is not set.")

def delete_test_cookie(request):
    response = HttpResponse("Deleting the test cookie")
    response.delete_cookie('test_cookie')
    return response

myappF23/templates/myappF23/about.html
{% extends 'myappF23/base.html' %}
{% block myhdg %}
Hello Megha Bhargava
{% endblock %}
{% block body_block %}
<h2>This is a Distance Education Website! Search our Categories to find all available Courses.</h2>
{% endblock %}

myappF23/templates/myappF23/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
        <div>
            <h1>{% block myhdg %}Hello User {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
        <div>
        	<ul>
                <li class="hbar1"><a href="/myappF23/about/">Find out about our E-Learning site</a></li>
                <li class="hbar1"><a href = "{% url 'myappF23:index' %}">Click here to return to main page</a><br/></li>
                <li class="hbar1"><a href = "{% url 'myappF23:courses' %}">Courses</a><br/></li>
            </ul>
        </div>
    </body>
</html>

myappF23/templates/myappF23/coursedetail.html
{% extends 'myappF23/base.html' %}
{% block myhdg %}
Hello Megha Bhargava
{% endblock %}

{% block body_block %}
<h2>{{ course.title }}</h2>
<p>Interested: {{ course.interested }}</p>
<p>Price: {{ course.price }}</p>
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Express Interest</button>
</form>
{% endblock%}

myappF23/templates/myappF23/courses.html
{% extends 'myappF23/base.html' %}

{% block myhdg %}
Hello Megha Bhargava
{% endblock %}

{% block body_block %}
<ul>
    {% for course in courses %}
    <li><a href="{% url 'myappF23:courses_detail' course.id%}">{{course.title}}({{course.price}})</a></li>
    {% endfor %}
</ul>
<a href="{% url 'myappF23:place_order' %}">Place an Order</a>

{% endblock %}

myappF23/templates/myappF23/detail.html
{% extends 'myappF23/base.html' %}

{% block myhdg %}
Hello Megha Bhargava
{% endblock %}

{% block body_block %}

<p><b>{{category}}</b></p>
    {% for course in courses %}
        <li>{{course.title}}</li>
    {% endfor %}
{% endblock %}

myappF23/templates/myappF23/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>

<p><b>{{category}}</b></p>
    {% for course in courses %}
        <li>{{course.title}}</li>
    {% endfor %}
<a href="{% url 'myappF23:index' %}">Home(Namespace)</a>
</body>
</html>

myappF23/templates/myappF23/index.html
{% extends 'myappF23/base.html' %}
{% block myhdg %}
Hello Megha Bhargava
{% endblock %}
{% block body_block %}

    {% if category_list %}
        <h2>List of Categories</h2>
        <ol>
            {% for category  in category_list %}
                <li> <a href="{% url 'myappF23:detail' category_no=category.pk %}"> {{ category.name}} </a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}

        {% if instructor_list %}
        <h2>List of Instructors</h2>
        <ol>
            {% for instructor  in instructor_list %}
                <li> <a href="{% url 'myappF23:instructor_detail' instructor_id=instructor.pk %}"> {{ instructor.first_name}} {{instructor.last_name}} </a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available Instructors!</strong>
    {% endif %}
    <p>Cookies count: {{cookie_count}}</p>
    <p>{{message}}</p>
{% endblock %}

myappF23/templates/myappF23/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    {% if category_list %}
        <h2>List of Categories</h2>
        <ol>
            {% for category  in category_list %}
                <li> <a href="{% url 'myappF23:detail' category_no=category.pk %}"> {{ category.name}} </a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}

        {% if instructor_list %}
        <h2>List of Instructors</h2>
        <ol>
            {% for instructor  in instructor_list %}
                <li> <a href="{% url 'myappF23:instructor_detail' instructor_id=instructor.pk %}"> {{ instructor.first_name}} {{instructor.last_name}} </a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available Instructors!</strong>
    {% endif %}

<p><a href="{% url 'myappF23:about' %}">About page</a></p>
</body>
</html>

myappF23/templates/myappF23/instructor_detail.html
{% extends 'myappF23/base.html' %}
{% block myhdg %}
Hello Megha Bhargava
{% endblock %}
{% block body_block %}

<body>

<p><b>{{instructor.first_name}} {{instructor.last_name}}</b></p>
<h2>List of courses</h2>
<ul>
    {% for course in courses %}
        <li>{{course.title}}</li>
    {% endfor %}
</ul>
<h2>List of Students</h2>
<ul>
{% for student in students %}
        <li>{{student.first_name}} {{student.last_name}}</li>
    {% endfor %}
    </ul>
{% endblock %}

myappF23/templates/myappF23/login.html
{% extends 'myappF23/base.html' %}
{% block myhdg %}
Hello Megha Bhargava
{% endblock %}

{% block body_block %}
 <h2>Login</h2>
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

myappF23/templates/myappF23/myaccount.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Welcome to Your Account, {{ user.get_full_name }}</h1>

    {% if is_student %}
        <h2>Courses Ordered:</h2>
        <ul>
            {% for course in courses_ordered %}
                <li>{{ course.course.title }}- {{course.order_price}}</li>
            {% endfor %}
        </ul>

        <h2>Courses Interested In:</h2>
        <ul>
            {% for course in courses_interested %}
                <li>{{ course.title }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You are not a registered student!</p>
    {% endif %}

    <a href="{% url 'myappF23:logout' %}">Logout</a>
</body>
</html>

myappF23/templates/myappF23/order_response.html
{% extends 'myappF23/base.html' %}
{% block myhdg %}
Hello Megha Bhargava
{% endblock %}

{% block body_block %}
  <h2>Order Response</h2>
  <p>{{ msg }}</p>
  <a href="{% url 'myappF23:place_order' %}">Back to Place Order</a>
{% endblock %}

myappF23/templates/myappF23/placeorder.html
{% extends 'myappF23/base.html' %}
{% block myhdg %}
Hello Megha Bhargava
{% endblock %}
{% block body_block %}
  <h2>Place Order</h2>
  <form method="post" action="{% url 'myappF23:place_order' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Place Order</button>
  </form>
  <ul>
    {% for course in courlist %}
      <li>{{ course.title }} - ${{ course.price }}</li>
    {% endfor %}
  </ul>
{% endblock %}

myappF23/templates/myappF23/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>

<p><b>{{category}}</b></p>

<a href="{% url 'myappF23:index' %}">Home(Namespace)</a>
</body>
</html>